In [5]:
from fVIT import VisionTransformer, _vision_transformer

In [7]:
model = _vision_transformer(
        patch_size=16,
        num_layers=12,
        input_emb_dim = 384,
        num_heads=12,
        hidden_dim=768,
        mlp_dim=3072,
        progress=True,
        pretrained=False,
        arch = ''
    )

In [8]:
model

VisionTransformer(
  (conv_proj): Linear(in_features=384, out_features=768, bias=True)
  (encoder): Encoder(
    (dropout): Dropout(p=0.0, inplace=False)
    (layers): Sequential(
      (encoder_layer_0): EncoderBlock(
        (ln_1): LayerNorm((768,), eps=1e-06, elementwise_affine=True)
        (self_attention): MultiheadAttention(
          (out_proj): NonDynamicallyQuantizableLinear(in_features=768, out_features=768, bias=True)
        )
        (dropout): Dropout(p=0.0, inplace=False)
        (ln_2): LayerNorm((768,), eps=1e-06, elementwise_affine=True)
        (mlp): MLPBlock(
          (0): Linear(in_features=768, out_features=3072, bias=True)
          (1): GELU(approximate='none')
          (2): Dropout(p=0.0, inplace=False)
          (3): Linear(in_features=3072, out_features=768, bias=True)
          (4): Dropout(p=0.0, inplace=False)
        )
      )
      (encoder_layer_1): EncoderBlock(
        (ln_1): LayerNorm((768,), eps=1e-06, elementwise_affine=True)
        (self_at

In [2]:
import torch
import numpy
from torch import nn 
pt_file = torch.load('SOB_B_A-14-22549AB-40-010.pt')

In [3]:
inp = pt_file[0].unfold(1, 16, 16).transpose(1,2)

In [4]:
inp.shape
# x = inp.flatten(2, 3).transpose(1,2)

torch.Size([1, 384, 16, 16])

In [9]:
num_ftrs = model.heads.head.in_features
model.heads.head = nn.Linear(num_ftrs, 8)


In [8]:
model.eval()

VisionTransformer(
  (conv_proj): Linear(in_features=384, out_features=768, bias=True)
  (encoder): Encoder(
    (dropout): Dropout(p=0.0, inplace=False)
    (layers): Sequential(
      (encoder_layer_0): EncoderBlock(
        (ln_1): LayerNorm((768,), eps=1e-06, elementwise_affine=True)
        (self_attention): MultiheadAttention(
          (out_proj): NonDynamicallyQuantizableLinear(in_features=768, out_features=768, bias=True)
        )
        (dropout): Dropout(p=0.0, inplace=False)
        (ln_2): LayerNorm((768,), eps=1e-06, elementwise_affine=True)
        (mlp): MLPBlock(
          (0): Linear(in_features=768, out_features=3072, bias=True)
          (1): GELU(approximate='none')
          (2): Dropout(p=0.0, inplace=False)
          (3): Linear(in_features=3072, out_features=768, bias=True)
          (4): Dropout(p=0.0, inplace=False)
        )
      )
      (encoder_layer_1): EncoderBlock(
        (ln_1): LayerNorm((768,), eps=1e-06, elementwise_affine=True)
        (self_at

In [10]:
model.cuda()

VisionTransformer(
  (conv_proj): Linear(in_features=384, out_features=768, bias=True)
  (encoder): Encoder(
    (dropout): Dropout(p=0.0, inplace=False)
    (layers): Sequential(
      (encoder_layer_0): EncoderBlock(
        (ln_1): LayerNorm((768,), eps=1e-06, elementwise_affine=True)
        (self_attention): MultiheadAttention(
          (out_proj): NonDynamicallyQuantizableLinear(in_features=768, out_features=768, bias=True)
        )
        (dropout): Dropout(p=0.0, inplace=False)
        (ln_2): LayerNorm((768,), eps=1e-06, elementwise_affine=True)
        (mlp): MLPBlock(
          (0): Linear(in_features=768, out_features=3072, bias=True)
          (1): GELU(approximate='none')
          (2): Dropout(p=0.0, inplace=False)
          (3): Linear(in_features=3072, out_features=768, bias=True)
          (4): Dropout(p=0.0, inplace=False)
        )
      )
      (encoder_layer_1): EncoderBlock(
        (ln_1): LayerNorm((768,), eps=1e-06, elementwise_affine=True)
        (self_at

In [11]:
inp.cuda()

tensor([[[[ 9.9816e-01,  1.1618e+00,  8.6519e-01,  ...,  1.0493e+00,
            9.7527e-01,  5.8005e-01],
          [ 8.2503e-01,  7.7003e-01,  9.1573e-01,  ...,  8.9481e-01,
            7.7280e-01,  9.1645e-01],
          [ 9.6720e-01,  7.5817e-01,  7.8673e-01,  ...,  1.0180e+00,
            7.1158e-01,  8.3776e-01],
          ...,
          [ 1.0258e+00,  1.2253e+00,  1.2885e+00,  ...,  7.9151e-01,
            6.5764e-01,  1.1177e+00],
          [ 1.1489e+00,  1.1680e+00,  1.1992e+00,  ...,  7.4528e-01,
            9.6577e-01,  9.9734e-01],
          [ 1.2162e+00,  1.2396e+00,  1.2188e+00,  ...,  5.9494e-01,
            9.0238e-01,  7.6658e-01]],

         [[-1.6534e-01,  1.7076e-01, -1.6117e-01,  ...,  8.5158e-02,
            5.2860e-02, -6.7185e-01],
          [-1.1809e-01,  3.6745e-01,  4.4402e-01,  ..., -1.1395e-01,
           -1.3214e-01, -5.0700e-04],
          [-1.1684e-01, -5.2720e-01, -7.5456e-02,  ..., -2.4627e-01,
           -1.1872e-01, -6.5448e-02],
          ...,
     

In [12]:
device = torch.device('cuda:0' if torch.cuda.is_available() else 'cpu')
model.to(device)
inp.to(device)

tensor([[[[ 9.9816e-01,  1.1618e+00,  8.6519e-01,  ...,  1.0493e+00,
            9.7527e-01,  5.8005e-01],
          [ 8.2503e-01,  7.7003e-01,  9.1573e-01,  ...,  8.9481e-01,
            7.7280e-01,  9.1645e-01],
          [ 9.6720e-01,  7.5817e-01,  7.8673e-01,  ...,  1.0180e+00,
            7.1158e-01,  8.3776e-01],
          ...,
          [ 1.0258e+00,  1.2253e+00,  1.2885e+00,  ...,  7.9151e-01,
            6.5764e-01,  1.1177e+00],
          [ 1.1489e+00,  1.1680e+00,  1.1992e+00,  ...,  7.4528e-01,
            9.6577e-01,  9.9734e-01],
          [ 1.2162e+00,  1.2396e+00,  1.2188e+00,  ...,  5.9494e-01,
            9.0238e-01,  7.6658e-01]],

         [[-1.6534e-01,  1.7076e-01, -1.6117e-01,  ...,  8.5158e-02,
            5.2860e-02, -6.7185e-01],
          [-1.1809e-01,  3.6745e-01,  4.4402e-01,  ..., -1.1395e-01,
           -1.3214e-01, -5.0700e-04],
          [-1.1684e-01, -5.2720e-01, -7.5456e-02,  ..., -2.4627e-01,
           -1.1872e-01, -6.5448e-02],
          ...,
     

In [13]:
out = model(inp)

torch.Size([1, 257, 768])
torch.Size([1, 257, 768])


In [26]:
out[0]

tensor([-0.2433,  1.2030,  0.1429, -1.2198, -0.7704, -0.0836, -0.8072,  0.5665],
       device='cuda:0', grad_fn=<SelectBackward0>)

In [15]:
import torch.nn.functional as F

In [16]:
s_out = F.softmax(out, dim=1)
s_out

tensor([[0.0856, 0.3638, 0.1260, 0.0323, 0.0506, 0.1005, 0.0487, 0.1925]],
       device='cuda:0', grad_fn=<SoftmaxBackward0>)

In [17]:
y_hat = torch.topk(out, 1, dim = 1)[1]

In [19]:
y_hat

tensor([[1]], device='cuda:0')

In [31]:
loss_fn = nn.CrossEntropyLoss()
loss_fn.to(device)

CrossEntropyLoss()

In [39]:
loss_fn.cuda()

CrossEntropyLoss()

In [35]:
logits = out[0]
logits.cuda()

tensor([-0.2433,  1.2030,  0.1429, -1.2198, -0.7704, -0.0836, -0.8072,  0.5665],
       device='cuda:0', grad_fn=<SelectBackward0>)

In [36]:
label = torch.tensor(2)
label.cuda()

tensor(2, device='cuda:0')

In [43]:
lss = loss_fn(logits.to(device), label.to(device))

In [44]:
lss

tensor(2.0713, device='cuda:0', grad_fn=<NllLossBackward0>)

In [45]:
from timm.utils import accuracy, AverageMeter

In [72]:
cc1 = accuracy_custom(logits.cuda(), label.cuda())

tensor([1], device='cuda:0')


RuntimeError: expand(torch.cuda.LongTensor{[1, 1]}, size=[1]): the number of sizes provided (1) must be greater or equal to the number of dimensions in the tensor (2)

In [52]:
ll = (logits,logits)

In [71]:
def accuracy_custom(output, target):
    """Computes the accuracy over the k top predictions for the specified values of k"""
    maxk = 1
    batch_size = 1
    _, pred = torch.topk(output, 1, 0,True, True)
    print(pred)
    pred = pred.t()
    correct = pred.eq(target.reshape(1, -1).expand_as(pred))
    return [correct[:min(k, maxk)].reshape(-1).float().sum(0) * 100. / batch_size for k in topk]

In [73]:
_, pred = torch.topk(logits.cuda(), 1, 0,True, True)

In [88]:
pred[0] + 1 == label_gpu 

tensor(True, device='cuda:0')

In [78]:
label_gpu = label.cuda()

In [86]:
label_gpu 

tensor(2, device='cuda:0')

In [87]:
pred

tensor([1], device='cuda:0')